[package]
name = "verifier"
version = "0.1.0"
authors = ["th0rgal <thomas@starknet.id>", "irisdv <iris@starknet.id>"]

[dependencies]
starknet = "2.3.1"
identity = { git = "https://github.com/starknet-id/identity.git", rev = "698debdfd63a1b366074685f58ebb779d201eeed" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false
